# Generated by Django 5.1.2 on 2025-10-02 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='カテゴリ名', max_length=100)),
                ('order', models.IntegerField(default=0, help_text='表示順')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'メニューカテゴリ',
                'verbose_name_plural': 'メニューカテゴリ',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '受注待ち'), ('confirmed', '確認済み'), ('preparing', '調理中'), ('ready', '準備完了'), ('delivered', '提供済み'), ('cancelled', 'キャンセル')], default='pending', max_length=20)),
                ('total_amount', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(help_text='ログイン用パスワード', max_length=255)),
                ('wifi_ssid', models.CharField(blank=True, help_text='WiFiのSSID', max_length=255, null=True)),
                ('wifi_password', models.CharField(blank=True, help_text='WiFiのパスワード', max_length=255, null=True)),
                ('wifi_security', models.CharField(choices=[('WPA', 'WPA/WPA2'), ('WEP', 'WEP'), ('nopass', 'なし（オープン）')], default='WPA', help_text='WiFiのセキュリティタイプ', max_length=10)),
                ('server_ip', models.GenericIPAddressField(blank=True, help_text='サーバーのIPアドレス（注文ページ用）', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '店舗設定',
                'verbose_name_plural': '店舗設定',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(help_text='テーブル番号', unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'テーブル',
                'verbose_name_plural': 'テーブル',
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='メニュー名', max_length=100)),
                ('description', models.TextField(blank=True, help_text='説明')),
                ('price', models.PositiveIntegerField(help_text='価格（円）')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('is_available', models.BooleanField(default=True, help_text='提供可能フラグ')),
                ('order', models.IntegerField(default=0, help_text='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qr.menucategory')),
            ],
            options={
                'verbose_name': 'メニュー項目',
                'verbose_name_plural': 'メニュー項目',
                'ordering': ['category__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(help_text='注文時の単価')),
                ('notes', models.TextField(blank=True, help_text='備考')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='qr.order')),
            ],
            options={
                'verbose_name': '注文項目',
                'verbose_name_plural': '注文項目',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='qr.table'),
        ),
    ]
